FROM alpine:latest

RUN apk --no-cache add git cmake clang clang-dev make gcc g++ libc-dev linux-headers boost-dev expat-dev zlib-dev bzip2-dev

RUN mkdir /osmium

WORKDIR /osmium

RUN git clone https://github.com/mapbox/protozero
RUN git clone https://github.com/osmcode/libosmium
RUN git clone https://github.com/osmcode/osmium-tool

RUN mkdir osmium-tool/build
WORKDIR /osmium/osmium-tool/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release
RUN make
RUN cp osmium /bin/osmium
WORKDIR /
